# This is a boilerplate parameters config generated for pipeline 'train_pycaret'
# using Kedro 0.18.3.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/0.18.3/kedro_project_setup/configuration.html#parameters
